import type { ParsedArtManifest } from './art-manifest';
import { BLIZZARD_LEGAL_FAQ, REPOSITORY_URL } from './shared';
import { wrap } from './notice';

/**
 * `public/maps/art/NOTICE.md` (terrain-navigation.md §13.4; D-033). Generated by `convert.ts`
 * from the facts its manifest records, so `validate.ts` (A3) can regenerate it offline and
 * compare. No timestamp. It names Blizzard Entertainment as the owner of the artwork, states
 * non-affiliation and D-033's four project rules, and draws no legal conclusion.
 */

/** Blizzard's Legal FAQ and the repository's address live in `shared.ts`, which every notice reads. */
export { BLIZZARD_LEGAL_FAQ, REPOSITORY_URL } from './shared';

const bullet = (text: string): string => wrap(text, '- ', '  ');
const numbered = (n: number, text: string): string => wrap(text, `${String(n)}. `, '   ');

const TYPE_NAMES: Readonly<Record<number, string>> = { 1: 'world', 2: 'continent', 3: 'zone or city', 6: 'battleground or small area' };

function describeKinds(manifest: ParsedArtManifest): string {
  const counts = new Map<number, number>();
  for (const f of manifest.files) counts.set(f.uiMapType, (counts.get(f.uiMapType) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([type, n]) => `${String(n)} ${TYPE_NAMES[type] ?? `type-${String(type)}`} map${n === 1 ? '' : 's'}`)
    .join(', ');
}

export function artNoticeText(manifest: ParsedArtManifest): string {
  const { client } = manifest;
  const overlays = manifest.files.reduce((n, f) => n + f.overlays.length, 0);
  const tiles = manifest.files.reduce((n, f) => n + f.tiles.length + f.overlays.reduce((k, o) => k + o.tiles.length, 0), 0);
  const tables = manifest.tables.map((t) => `\`${t.table}\` (${String(t.fileDataId)})`).join(', ');
  const encoder = manifest.encoder;
  const webp = manifest.webp;
  const blocks: readonly string[] = [
    '# Painted map art: notice',
    wrap(
      'Generated by `tools/maps/convert.ts`. Do not edit these files by hand; regenerate them with `pnpm tsx tools/maps/convert.ts` ' +
        '(it needs the pinned client at `WOW_INSTALL`) and check them with `pnpm maps:validate`.',
    ),
    '## What these files are',
    wrap(
      manifest.deployment === null
        ? `${String(manifest.files.length)} WebP images of the World of Warcraft world map's painted art (${describeKinds(manifest)}), one per UiMap ` +
            `that has art in the World of Warcraft: Forever client (\`${client.product}\` ${client.version}). Each is stitched from the client's ` +
            `\`UiMapArtTile\` textures with every \`WorldMapOverlay\` explored-area piece drawn in, so it shows the fully explored map ` +
            `(${String(tiles)} textures, ${String(overlays)} overlays in all). \`manifest.json\` lists every image with its SHA-256, pixel size, ` +
            'UiMap, world rectangle and input hash.'
        : `${String(manifest.files.length)} WebP images of the World of Warcraft world map's painted art (${describeKinds(manifest)}), of the ` +
            `${String(manifest.sources.length)} UiMaps that have art in the World of Warcraft: Forever client (\`${client.product}\` ${client.version}). ` +
            `${manifest.deployment.reason} Each image is stitched from the client's \`UiMapArtTile\` textures with every \`WorldMapOverlay\` ` +
            `explored-area piece drawn in, so it shows the fully explored map (${String(tiles)} textures, ${String(overlays)} overlays in all). ` +
            '`manifest.json` lists every image with its SHA-256, pixel size, UiMap, world rectangle and input hash, and keeps the pixel hash of ' +
            'every composed UiMap\'s image (`sources`), deployed or not.',
    ),
    '## Owner of the artwork',
    [
      bullet(
        'The artwork is Blizzard Entertainment\'s, © Blizzard Entertainment, Inc. It is extracted from the game client; it is not this ' +
          "project's work. World of Warcraft, Warcraft and Blizzard Entertainment are trademarks or registered trademarks of Blizzard " +
          'Entertainment, Inc.',
      ),
      bullet("This repository's GPL-3.0-or-later licence covers the project's own code and grants no rights over these images."),
    ].join('\n'),
    '## Why they are here (D-033)',
    wrap(
      "The project owner decided to publish the painted map art with this notice (docs/DECISIONS.md D-033). The owner's rationale is " +
        'recorded as stated, not verified: many third-party sites already show Blizzard\'s map art, and the owner believes Blizzard\'s ' +
        'policies allow this for fan sites. The decision draws no legal conclusion, and the owner accepts the risk. The governing source ' +
        `it records is Blizzard's Legal FAQ, section "Copyright/Trademark Policy for the Internet" (${BLIZZARD_LEGAL_FAQ}).`,
    ),
    wrap('The project follows four rules adopted from that page\'s conditions:'),
    [
      numbered(1, 'The site stays non-commercial: no ads, paid features or sales.'),
      numbered(2, 'Blizzard copyright and trademark notices accompany the art (this file, the About dialog and the README).'),
      numbered(3, `The art is removed promptly if Blizzard asks. Requests: ${REPOSITORY_URL}/issues.`),
      numbered(4, 'The project never distributes hacks, cheats or similar content.'),
    ].join('\n'),
    '## How they were made',
    [
      bullet(
        `Read-only from the local client's \`Data/\` folder through this project's CASC reader (\`tools/casc\`), pinned to ` +
          `\`${client.product}\` ${client.version}, build key \`${client.buildKey}\`. Nothing is fetched from the network.`,
      ),
      bullet(`Tables: ${tables}; layouts from WoWDBDefs (THIRD_PARTY_NOTICES "Format definitions").`),
      bullet(
        "BLP textures decoded by this project's own decoder (`tools/maps/lib/blp.ts`), stitched and composited at the client's pixel " +
          `positions, then encoded as lossy WebP by ${String(encoder['name'])} ${String(encoder['sharp'])} (libwebp ${String(encoder['libwebp'])}) at ` +
          `quality ${String(webp['quality'])}.`,
      ),
      bullet('No BLP, DB2 or other client file is committed or deployed; only these derived web images are.'),
    ].join('\n'),
    '## Non-affiliation',
    wrap('forever-route-lab is not affiliated with or endorsed by Blizzard Entertainment.'),
    `More: [docs/MAPS.md](${REPOSITORY_URL}/blob/main/docs/MAPS.md) §5, [docs/DECISIONS.md](${REPOSITORY_URL}/blob/main/docs/DECISIONS.md) ` +
      `D-033 and [THIRD_PARTY_NOTICES.md](${REPOSITORY_URL}/blob/main/THIRD_PARTY_NOTICES.md) ("Map art").`,
  ];
  return `${blocks.join('\n\n')}\n`;
}
