import { BLIZZARD_LEGAL_FAQ, REPOSITORY_URL } from './art-notice';
import type { ParsedAtlasManifest } from './atlas-manifest';
import { wrap } from './notice';

/**
 * `public/maps/atlas/NOTICE.md` (docs/research/map-atlas.md §7.4; D-033, D-042 O11). Generated by
 * `tools/maps/atlas.ts` from the facts its manifest records, so `validate.ts` (T1) can regenerate
 * it offline and compare. No timestamp. It names Blizzard Entertainment as the owner of the artwork,
 * lists every alteration the tiles make to it and every hidden label, states non-affiliation and
 * D-033's four project rules, and draws no legal conclusion.
 */

const bullet = (text: string): string => wrap(text, '- ', '  ');
const numbered = (n: number, text: string): string => wrap(text, `${String(n)}. `, '   ');

export function atlasNoticeText(manifest: ParsedAtlasManifest): string {
  const { client } = manifest;
  const tiles = manifest.files.filter((f) => f.path !== 'index.json').length;
  const drawn = manifest.sources.filter((s) => s.role !== 'read');
  const read = manifest.sources.filter((s) => s.role === 'read');
  const encoder = manifest.encoder;
  const webp = manifest.webp;
  const levelLabel = (levels: string): string => (levels === 'fine' ? 'at levels −1 and 0' : 'at every level');
  const blocks: readonly string[] = [
    '# Map atlas tiles: notice',
    wrap(
      'Generated by `tools/maps/atlas.ts`. Do not edit these files by hand; regenerate them with `pnpm tsx tools/maps/atlas.ts` ' +
        '(it needs the pinned client at `WOW_INSTALL`) and check them with `pnpm maps:validate`.',
    ),
    '## What these files are',
    wrap(
      `${String(tiles)} WebP tiles of one continuous map of Kalimdor and the Eastern Kingdoms, with Zephras Isle in a card between them, ` +
        `composed from ${String(drawn.length)} of the World of Warcraft world map's painted images (zones, cities and the Zephras Isle map) of the ` +
        `World of Warcraft: Forever client (\`${client.product}\` ${client.version}); ${String(read.length)} continent images were read for their ` +
        'land colouring and are not drawn. `index.json` tells the map which tiles exist; `manifest.json` lists every file with its SHA-256, ' +
        'every source image with its pixel hash, every parameter, the censuses and the alterations below.',
    ),
    '## Owner of the artwork',
    [
      bullet(
        "The artwork is Blizzard Entertainment's, © Blizzard Entertainment, Inc. It is extracted from the game client and composited by " +
          "this project's tool; it is not this project's work. World of Warcraft, Warcraft and Blizzard Entertainment are trademarks or " +
          'registered trademarks of Blizzard Entertainment, Inc.',
      ),
      bullet("This repository's GPL-3.0-or-later licence covers the project's own code and grants no rights over these images."),
    ].join('\n'),
    '## How the tiles alter the art (D-042 O11)',
    wrap('The owner decided these alterations are covered by composing the paintings seamlessly (docs/DECISIONS.md D-041 H, D-042 O11). The tiles:'),
    manifest.alterations.map((a) => numbered(a.id, a.what)).join('\n'),
    wrap(`Labels hidden by a mirror fill from the same painting (${String(manifest.hiddenLabels.length)}):`),
    manifest.hiddenLabels.map((h) => bullet(`${h.label} on the ${h.name} map (UiMap ${String(h.uiMapId)}), ${levelLabel(h.levels)}: ${h.reason}`)).join('\n'),
    wrap(
      'The masks, the tint\'s relief shading and the sea\'s distances come from this project\'s terrain byproducts (`public/maps/terrain/`, ' +
        'docs/DECISIONS.md D-032), which are derived from the client\'s terrain data, not from the painted art.',
    ),
    '## Why they are here (D-033)',
    wrap(
      "The project owner decided to publish the painted map art with a notice (docs/DECISIONS.md D-033) and to compose it into one map " +
        "(D-041 H, D-042). The owner's rationale is recorded as stated, not verified: many third-party sites already show Blizzard's map art, " +
        "and the owner believes Blizzard's policies allow this for fan sites. The decisions draw no legal conclusion, and the owner accepts " +
        `the risk. The governing source D-033 records is Blizzard's Legal FAQ, section "Copyright/Trademark Policy for the Internet" (${BLIZZARD_LEGAL_FAQ}).`,
    ),
    wrap("The project follows four rules adopted from that page's conditions:"),
    [
      numbered(1, 'The site stays non-commercial: no ads, paid features or sales.'),
      numbered(2, 'Blizzard copyright and trademark notices accompany the art (this file, the About dialog and the README).'),
      numbered(3, `The art is removed promptly if Blizzard asks. Requests: ${REPOSITORY_URL}/issues.`),
      numbered(4, 'The project never distributes hacks, cheats or similar content.'),
    ].join('\n'),
    '## How they were made',
    [
      bullet(
        `Read-only from the local client's \`Data/\` folder through this project's CASC reader (\`tools/casc\`), pinned to ` +
          `\`${client.product}\` ${client.version}, build key \`${client.buildKey}\`. Nothing is fetched from the network. Each source image is ` +
          'the same lossless raster `tools/maps/convert.ts` composes, checked against the pixel hash the art manifest records for it.',
      ),
      bullet(
        `Composited at 4 yards per pixel, reduced by 2×2 box filters for the coarser levels and recomposed at 2 and 1 yards per pixel where a ` +
          `painting or city plan is that fine, then encoded as lossy WebP by ${String(encoder['name'])} ${String(encoder['sharp'])} (libwebp ` +
          `${String(encoder['libwebp'])}) at quality ${String(webp['quality'])}.`,
      ),
      bullet('No BLP, DB2 or other client file is committed or deployed; only these derived web images are.'),
    ].join('\n'),
    '## Non-affiliation',
    wrap('forever-route-lab is not affiliated with or endorsed by Blizzard Entertainment.'),
    `More: [docs/research/map-atlas.md](${REPOSITORY_URL}/blob/main/docs/research/map-atlas.md), [docs/DECISIONS.md](${REPOSITORY_URL}/blob/main/docs/DECISIONS.md) ` +
      `D-033 and D-042, and [THIRD_PARTY_NOTICES.md](${REPOSITORY_URL}/blob/main/THIRD_PARTY_NOTICES.md) ("Map art").`,
  ];
  return `${blocks.join('\n\n')}\n`;
}
