import type { ParsedMinimapManifest } from './minimap-manifest';
import { MINIMAP_TILE_PATH } from './minimap-params';
import { wrap } from './notice';
import { BLIZZARD_LEGAL_FAQ, REPOSITORY_URL } from './shared';

/**
 * `public/maps/minimap/NOTICE.md` (docs/research/map-atlas.md §18.8; D-033, D-045, D-049). Generated
 * from the manifest, so check M1 can regenerate it offline and compare, and it is the first file of
 * the tile pack and the release's text (MM-06). No timestamp. It names Blizzard Entertainment as the
 * owner of the artwork, lists every alteration and what is kept as drawn, states non-affiliation,
 * D-033's four project rules and how removal works, and draws no legal conclusion.
 */

const bullet = (text: string): string => wrap(text, '- ', '  ');
/** A whole number with thousands separators (no locale: the text must not depend on the machine). */
const thousands = (n: number): string => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const numbered = (n: number, text: string): string => wrap(text, `${String(n)}. `, '   ');

type Json = Readonly<Record<string, unknown>>;
const isRecord = (value: unknown): value is Json => typeof value === 'object' && value !== null && !Array.isArray(value);
const count = (value: unknown): number | null => (typeof value === 'number' && Number.isInteger(value) && value >= 0 ? value : null);

/**
 * How far alteration 1 reaches onto dry ground, from the manifest's own census (review finding
 * MD-05): per map, the texels on quads the liquid grid calls dry that the recolour moved by half or
 * more, and those it brightened. Empty when the census does not record them.
 */
function dryGroundLine(manifest: ParsedMinimapManifest): string[] {
  const census = manifest.raw['census'];
  const maps = isRecord(census) && isRecord(census['maps']) ? census['maps'] : null;
  if (maps === null) return [];
  const rows = manifest.maps.map((m) => {
    const entry = maps[String(m.mapId)];
    const dry = isRecord(entry) && isRecord(entry['dry']) ? entry['dry'] : null;
    return { name: m.name, half: count(dry?.['recolouredHalf']), brightened: count(dry?.['brightened']) };
  });
  if (rows.some((r) => r.half === null || r.brightened === null)) return [];
  const brightened = rows.reduce((s, r) => s + (r.brightened ?? 0), 0);
  return [
    wrap(
      'How far the recolour reaches onto dry ground, from the census in `manifest.json` (native texels, before the resample): texels on ground the ' +
        `terrain data calls dry, recoloured by half or more (weight 0.5 or over): ${rows.map((r) => `${r.name} ${thousands(r.half ?? 0)}`).join(', ')}; ` +
        `texels brightened: ${thousands(brightened)}.`,
    ),
  ];
}

export function minimapNoticeText(manifest: ParsedMinimapManifest): string {
  const { client } = manifest;
  const tiles = manifest.files.filter((f) => MINIMAP_TILE_PATH.test(f.path)).length;
  const maps = manifest.maps.map((m) => `${m.name} (map ${String(m.mapId)}, ${thousands(m.tiles)} textures)`).join(', ');
  const textures = manifest.maps.reduce((s, m) => s + m.tiles, 0);
  const encoder = manifest.encoder;
  const webp = manifest.webp;
  const blocks: readonly string[] = [
    '# Minimap tiles: notice',
    wrap(
      'Generated by `tools/maps/minimap.ts`. Do not edit these files by hand; regenerate them with `pnpm tsx tools/maps/minimap.ts` ' +
        '(it needs the pinned client at `WOW_INSTALL`) and check them with `pnpm tsx tools/maps/minimap.ts --check`.',
    ),
    '## What these files are',
    wrap(
      `${thousands(tiles)} WebP tiles of one continuous map of Kalimdor and the Eastern Kingdoms, with Zephras Isle in a card between them, ` +
        `made from the ${thousands(textures)} minimap textures of the World of Warcraft: Forever client (\`${client.product}\` ` +
        `${client.version}): ${maps}. \`index.json\` tells the map which tiles exist; \`manifest.json\` lists every file with its SHA-256, every ` +
        'source texture with its FileDataID and content key, every parameter, the census and the alterations below. The tiles are not kept in ' +
        "the project's git history: they are published as a release asset (a tar holding this notice first, then the manifest and the tiles), " +
        'which `pack.json` names and pins by SHA-256.',
    ),
    '## Owner of the artwork',
    [
      bullet(
        "The artwork is Blizzard Entertainment's, © Blizzard Entertainment, Inc. It is extracted from the game client and altered by this " +
          "project's tool; it is not this project's work. World of Warcraft, Warcraft and Blizzard Entertainment are trademarks or registered " +
          'trademarks of Blizzard Entertainment, Inc.',
      ),
      bullet("This repository's GPL-3.0-or-later licence covers the project's own code and grants no rights over these images."),
    ].join('\n'),
    '## How the tiles alter the textures (D-049 O15)',
    wrap('The owner decided (docs/DECISIONS.md D-045, D-049) that the sea is recoloured to one navy and the maps are drawn as one. The tiles alter the textures as follows:'),
    manifest.alterations.map((a) => numbered(a.id, a.what)).join('\n'),
    ...dryGroundLine(manifest),
    wrap('Kept as drawn:'),
    manifest.kept.map((k) => bullet(k)).join('\n'),
    wrap(
      "The liquid areas that gate the recolour come from the client's terrain data (the same grid as this project's terrain byproducts, " +
        '`public/maps/terrain/`, docs/DECISIONS.md D-032), not from the textures.',
    ),
    '## Why they are here (D-033, D-045)',
    wrap(
      'The project owner decided to publish Blizzard\'s map art with a notice (docs/DECISIONS.md D-033) and extended that decision to the ' +
        "client's minimap textures (D-045), on the same terms. The owner's rationale is recorded as stated, not verified: many third-party " +
        "sites already show Blizzard's map art, and the owner believes Blizzard's policies allow this for fan sites. The decisions draw no " +
        `legal conclusion, and the owner accepts the risk. The governing source D-033 records is Blizzard's Legal FAQ, section "Copyright/Trademark Policy for the Internet" (${BLIZZARD_LEGAL_FAQ}).`,
    ),
    wrap("The project follows four rules adopted from that page's conditions:"),
    [
      numbered(1, 'The site stays non-commercial: no ads, paid features or sales.'),
      numbered(2, 'Blizzard copyright and trademark notices accompany the art (this file, inside every copy of the tile pack, the About dialog and the README).'),
      numbered(
        3,
        `The art is removed promptly if Blizzard asks: the release asset is deleted, the pointer is removed, the site is redeployed and the tile addresses are confirmed gone. Copies that others have already downloaded cannot be recalled. Requests: ${REPOSITORY_URL}/issues.`,
      ),
      numbered(4, 'The project never distributes hacks, cheats or similar content.'),
    ].join('\n'),
    '## How they were made',
    [
      bullet(
        `Read-only from the local client's \`Data/\` folder through this project's CASC reader (\`tools/casc\`), pinned to \`${client.product}\` ` +
          `${client.version}, build key \`${client.buildKey}\`. Nothing is fetched from the network. The textures are found through each map's WDT ` +
          '(its MAID chunk) and decoded (BLP2 DXT1, 512 × 512) by our own code.',
      ),
      bullet(
        'Recoloured in texel space, stitched onto the atlas grid, resampled to 1 yard per pixel and reduced by 2 × 2 box filters for the coarser ' +
          `levels, then encoded as lossy WebP by ${String(encoder['name'])} ${String(encoder['sharp'])} (libwebp ${String(encoder['libwebp'])}) at quality ` +
          `${String(webp['quality'])}.`,
      ),
      bullet('No BLP, WDT, ADT, DB2 or other client file is committed, published or deployed; only these derived web images are.'),
    ].join('\n'),
    '## Non-affiliation',
    wrap('forever-route-lab is not affiliated with or endorsed by Blizzard Entertainment.'),
    `More: [docs/research/map-atlas.md](${REPOSITORY_URL}/blob/main/docs/research/map-atlas.md) Part II, [docs/DECISIONS.md](${REPOSITORY_URL}/blob/main/docs/DECISIONS.md) ` +
      'D-033, D-045 and D-049.',
  ];
  return `${blocks.join('\n\n')}\n`;
}
