/**
 * `public/maps/placeholder/NOTICE.md` (docs/MAPS.md §8.2; DATA_PROVENANCE §3.2, §7). Generated by
 * `import.ts --placeholder` together with the geometry, so it always names the inputs the
 * geometry was built from. It contains no timestamp, so identical inputs give identical bytes.
 */

/** DATA_PROVENANCE §3.2 "Carve-out (LIC-10)", verbatim (a test checks it against that file). */
export const CARVE_OUT =
  "GPL-3.0-or-later applies to this project's contributions and, as a posture, to Questie-derived data; it grants no rights over Blizzard content (names, text, client-derived values) or other third-party material embedded in that data.";

export interface NoticeFacts {
  readonly questiedbRepo: string;
  readonly commit: string;
  readonly conversionPath: string;
  readonly conversionSha256: string;
  readonly frameBuild: string;
  readonly eraBuild: string;
  readonly frameCount: number;
  readonly eraUiMapIds: readonly number[];
  readonly db2Build: string;
  readonly db2RowCount: number;
  readonly db2UiMaps: readonly { readonly id: number; readonly name: string; readonly rows: number }[];
  readonly rowsFile: string;
  readonly rowsFileSha256: string;
  readonly csvSha256: { readonly UiMapAssignment: string; readonly UiMap: string };
  readonly frameHash: string;
  readonly contentHash: string;
  /** upstream.json `licenceCheck.date` (data-F9). */
  readonly licenceCheckDate: string;
}

const WIDTH = 100;

/** Wraps `text` at word boundaries to `WIDTH` columns; continuation lines get `indent`. Deterministic. */
export function wrap(text: string, firstPrefix = '', indent = ''): string {
  const lines: string[] = [];
  let line = firstPrefix;
  let empty = true;
  for (const word of text.split(' ')) {
    if (!empty && line.length + 1 + word.length > WIDTH) {
      lines.push(line);
      line = indent + word;
    } else line = empty ? line + word : `${line} ${word}`;
    empty = false;
  }
  lines.push(line);
  return lines.join('\n');
}

const bullet = (text: string): string => wrap(text, '- ', '  ');

const list = (items: readonly string[]): string =>
  items.length <= 1 ? items.join('') : `${items.slice(0, -1).join(', ')} and ${items[items.length - 1] ?? ''}`;

export function noticeText(facts: NoticeFacts): string {
  const uiMaps = list(facts.db2UiMaps.map((m) => `${m.name} ${String(m.id)}${m.rows > 1 ? ` (${String(m.rows)} rows, one per continent)` : ''}`));
  const blocks: readonly string[] = [
    '# Placeholder map geometry: notice',
    wrap(
      'Generated by `tools/maps/import.ts --placeholder`. Do not edit these files by hand; regenerate them with `pnpm maps:placeholder` ' +
        '(the same as `pnpm tsx tools/maps/import.ts --placeholder`) and check them with `pnpm maps:validate`.',
    ),
    '## What these files are',
    wrap(
      '`geometry.placeholder.json` holds zone frames and map metadata for the procedural placeholder map: the world-yard rectangle of ' +
        'every UiMap, its world map, its name, and the Era→Forever coefficients of the four changed zones. It contains no map art, no ' +
        'terrain and no images.',
    ),
    wrap(
      `Frame hash of the ${String(facts.frameCount)} QuestieDB frames (docs/MAPS.md §5.6): \`${facts.frameHash}\`. Content hash of every ` +
        `row, name, parent and coefficient (docs/MAPS.md §5.3), which the app checks before it uses the file: \`${facts.contentHash}\`.`,
    ),
    '## Origin 1: QuestieDB `conversion.json`',
    [
      bullet(
        `${String(facts.frameCount)} zone frames (\`source: "questiedb-conversion"\`, build ${facts.frameBuild}) and the Era→Forever ` +
          `coefficients of UiMaps ${list(facts.eraUiMapIds.map(String))} (Era build ${facts.eraBuild}), copied from \`${facts.conversionPath}\` ` +
          `(\`geometry.transforms[].target_bounds\` and \`coefficients\`) of ${facts.questiedbRepo} at commit \`${facts.commit}\`.`,
      ),
      bullet(`Input: the LF git blob of that file, SHA-256 \`${facts.conversionSha256}\`.`),
      bullet(
        'These are Questie/QuestieDB-derived values. They derive in turn from Blizzard client DBC exports ' +
          `(builds ${facts.eraBuild} and ${facts.frameBuild}).`,
      ),
    ].join('\n'),
    `## Origin 2: Blizzard client values at ${facts.db2Build}`,
    [
      bullet(
        `${String(facts.db2RowCount)} \`UiMapAssignment\` rows for ${String(facts.db2UiMaps.length)} UiMaps (\`source: "db2-csv"\`, ` +
          `build ${facts.db2Build}): ${uiMaps}; with those UiMaps' \`Name_lang\`, \`Type\` and \`ParentUiMapID\` from \`UiMap\`.`,
      ),
      bullet(
        'They are Blizzard client values. The two CSVs they were taken from were fetched on 2026-09-25 from wago.tools as individual ' +
          `requests during research, not by scripted crawling (\`UiMapAssignment\` SHA-256 \`${facts.csvSha256.UiMapAssignment}\`, ` +
          `\`UiMap\` SHA-256 \`${facts.csvSha256.UiMap}\`). No tool fetches them (D-011).`,
      ),
      bullet(
        `The rows are committed with table, build and row-ID citations in \`${facts.rowsFile}\` (SHA-256 of its LF bytes ` +
          `\`${facts.rowsFileSha256}\`), by owner decision (D-018).`,
      ),
      bullet(
        'The owner states that the Forever beta has no NDA; individual client-derived values may appear in this repository when they ' +
          'cite table, build and column (D-022). Together with the QuestieDB frames, these rows make up the whole `UiMapAssignment` ' +
          `table at ${facts.db2Build}, an explicit exception to "bulk client tables stay local" (D-026).`,
      ),
    ].join('\n'),
    '## Licence finding and posture',
    [
      bullet(
        "Questie/Questie and Questie/QuestieDB have no root licence file (none covering Questie's own code or data), and have " +
          `never had one on their default branches (full-history check, ${facts.licenceCheckDate}). The licence files in Questie's subfolders cover ` +
          "bundled third-party material only. The draft `LICENSE.md` on Questie's unmerged `license` branch says that, when in " +
          'doubt, Questie should be considered "all rights reserved".',
      ),
      bullet("The owner's posture is to publish these derived files with prominent notices, accepting the risk (D-016)."),
      bullet('The carve-out, verbatim from docs/DATA_PROVENANCE.md §3.2 (as in `data/NOTICE.md`):'),
    ].join('\n'),
    `> ${CARVE_OUT}`,
    'This is not a legal conclusion.',
    '## Non-affiliation',
    wrap(
      'forever-route-lab is not affiliated with or endorsed by Blizzard Entertainment or the Questie project. World of Warcraft is a ' +
        'trademark of Blizzard Entertainment, Inc.',
    ),
    'More: [docs/MAPS.md](https://github.com/laurencestokes/forever-route-lab/blob/main/docs/MAPS.md) §8, ' +
      '[docs/DATA_PROVENANCE.md](https://github.com/laurencestokes/forever-route-lab/blob/main/docs/DATA_PROVENANCE.md) and ' +
      '[THIRD_PARTY_NOTICES.md](https://github.com/laurencestokes/forever-route-lab/blob/main/THIRD_PARTY_NOTICES.md) ("Map geometry").',
  ];
  return `${blocks.join('\n\n')}\n`;
}
