import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { layoutFromDbd } from '../../../casc/dbd';
import { LAYOUT_BUILD, WOWDBDEFS_COMMIT, WOWDBDEFS_REPOSITORY } from '../../../casc/layout-source';
import type { Wdc5Layout } from '../../../casc/wdc5';

/**
 * Generates `tools/maps/lib/client-data/layouts.ts`: the WDC5 layouts of the five client tables
 * the committed client tables read (docs/research/map-presentation.md §16, D-039 B and E) that
 * `tools/casc/layouts.ts` does not carry. They live here, not in `tools/casc/layouts.ts`, so that
 * adding them does not change the tool tree hashes the navigation build and the terrain
 * byproducts record over `tools/casc` (their gates would fail until rebuilt).
 *
 * The inputs are the same kind of research copies as `tools/casc/layout-source.ts` reads:
 * WoWDBDefs `definitions/<Table>.dbd` and `manifest.json` at the pinned commit, fetched during
 * research as individual requests into gitignored folders. No tool downloads them.
 */

export const CLIENT_LAYOUT_TABLES = ['ContentTuning', 'LFGDungeons', 'TaxiNodes', 'TaxiPath', 'TaxiPathNode'] as const;
export type ClientLayoutTable = (typeof CLIENT_LAYOUT_TABLES)[number];

/** Research folders holding the `.dbd` copies and `dbd-manifest.json`, repository-relative, searched in order. */
export const DEFAULT_CLIENT_DBD_DIRS: readonly string[] = ['.cache/experiments/maps', '.cache/map-presentation/data/dbd'];

export const CLIENT_LAYOUTS_FILE = 'tools/maps/lib/client-data/layouts.ts';

export interface GeneratedClientTable {
  readonly fileDataId: number;
  readonly layout: Wdc5Layout;
}

function finder(repoRoot: string, dirs: readonly string[]): (file: string) => string | null {
  return (file) => {
    for (const dir of dirs) {
      const path = join(repoRoot, dir, file);
      if (existsSync(path)) return path;
    }
    return null;
  };
}

/** True when every research copy the generator needs is present. */
export function clientLayoutSourcesPresent(repoRoot: string, dirs: readonly string[] = DEFAULT_CLIENT_DBD_DIRS): boolean {
  const find = finder(repoRoot, dirs);
  return find('dbd-manifest.json') !== null && CLIENT_LAYOUT_TABLES.every((table) => find(`${table}.dbd`) !== null);
}

/** Every table's layout and FileDataID from the research copies. Throws when one is missing. */
export function readClientLayoutSources(repoRoot: string, dirs: readonly string[] = DEFAULT_CLIENT_DBD_DIRS): ReadonlyMap<ClientLayoutTable, GeneratedClientTable> {
  const find = finder(repoRoot, dirs);
  const need = (file: string): string => {
    const path = find(file);
    if (path === null) throw new Error(`${file} is in none of ${dirs.join(', ')}`);
    return path;
  };
  const manifest = JSON.parse(readFileSync(need('dbd-manifest.json'), 'utf8')) as readonly { readonly tableName?: string; readonly db2FileDataID?: number }[];
  const out = new Map<ClientLayoutTable, GeneratedClientTable>();
  for (const table of CLIENT_LAYOUT_TABLES) {
    const entry = manifest.find((e) => e.tableName === table);
    if (entry?.db2FileDataID === undefined) throw new Error(`dbd-manifest.json has no db2FileDataID for ${table}`);
    const source = `WoWDBDefs ${WOWDBDEFS_COMMIT} definitions/${table}.dbd`;
    out.set(table, { fileDataId: entry.db2FileDataID, layout: layoutFromDbd(table, readFileSync(need(`${table}.dbd`), 'utf8'), LAYOUT_BUILD, source) });
  }
  return out;
}

/** The text of `layouts.ts`: deterministic, LF, one table per entry in `CLIENT_LAYOUT_TABLES` order. */
export function renderClientLayoutsModule(tables: ReadonlyMap<ClientLayoutTable, GeneratedClientTable>): string {
  const lines: string[] = [
    '/**',
    ' * GENERATED by `pnpm tsx tools/maps/client-tables.ts --layouts` from WoWDBDefs; do not edit by hand.',
    ' *',
    ` * Source: ${WOWDBDEFS_REPOSITORY} at commit ${WOWDBDEFS_COMMIT}: the`,
    ` * \`definitions/<Table>.dbd\` block for build ${LAYOUT_BUILD} and \`manifest.json\` (FileDataIDs).`,
    ' * WoWDBDefs licenses its `definitions/` as CC BY-SA 4.0 (its LICENSE.md, same blob at that',
    ' * commit and on master, checked 2026-09-26). This file adapts those definitions (field names,',
    ' * types, sizes and order) into TypeScript data; see THIRD_PARTY_NOTICES.md "Format definitions"',
    ' * and "Client-derived tables".',
    ' */',
    "import type { Db2Table } from '../../../casc/layouts';",
    '',
    `export const CLIENT_LAYOUT_BUILD = '${LAYOUT_BUILD}';`,
    '',
    'export const CLIENT_DB2 = {',
  ];
  for (const table of CLIENT_LAYOUT_TABLES) {
    const entry = tables.get(table);
    if (entry === undefined) throw new Error(`no layout for ${table}`);
    const l = entry.layout;
    lines.push(`  ${table}: {`);
    lines.push(`    fileDataId: ${String(entry.fileDataId)},`);
    lines.push('    layout: {');
    lines.push(`      table: '${l.table}',`);
    lines.push(`      layoutHash: '${l.layoutHash}',`);
    lines.push(`      id: '${l.id}',`);
    lines.push(`      idInline: ${String(l.idInline)},`);
    lines.push(`      relation: ${l.relation === null ? 'null' : `'${l.relation}'`},`);
    lines.push(`      relationInline: ${String(l.relationInline)},`);
    lines.push(`      source: '${l.source}',`);
    lines.push('      fields: [');
    for (const f of l.fields) lines.push(`        { name: '${f.name}', type: '${f.type}', bits: ${String(f.bits)}, array: ${String(f.array)} },`);
    lines.push('      ],');
    lines.push('    },');
    lines.push('  },');
  }
  lines.push('} as const satisfies Record<string, Db2Table>;');
  lines.push('');
  lines.push('export type ClientDb2TableName = keyof typeof CLIENT_DB2;');
  lines.push('');
  return lines.join('\n');
}
