import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { layoutFromDbd } from './dbd';
import { CascError } from './errors';
import type { Wdc5Layout } from './wdc5';

/**
 * Generates `tools/casc/layouts.ts` from WoWDBDefs files (`make-layouts.ts`), and lets a test
 * check the committed file against them when the research copies are present.
 *
 * The inputs are the research copies of WoWDBDefs `definitions/<Table>.dbd` and `manifest.json`
 * at the pinned commit, fetched during research as individual requests (docs/MAPS.md §8.3) into
 * gitignored folders. No tool downloads them.
 */

export const WOWDBDEFS_COMMIT = 'cf84e010f84ba9c8d48fd61730f92bf0d8f2b1cd';
export const WOWDBDEFS_REPOSITORY = 'https://github.com/wowdev/WoWDBDefs';
/** The build whose definition blocks are copied (the Forever pin, D-013 / terrain-navigation §2). */
export const LAYOUT_BUILD = '1.60.1.70009';

/** Tables the terrain (3b.1-3b.4) and map-art (3b.8) pipelines read. */
export const LAYOUT_TABLES = [
  'AreaTable',
  'GameObjects',
  'LiquidType',
  'Map',
  'TransportAnimation',
  'UiMap',
  'UiMapArt',
  'UiMapArtStyleLayer',
  'UiMapArtTile',
  'UiMapAssignment',
  'UiMapXMapArt',
  'WMOAreaTable',
  'WorldMapOverlay',
  'WorldMapOverlayTile',
] as const;
export type LayoutTable = (typeof LAYOUT_TABLES)[number];

/** Research folders holding the `.dbd` copies and `dbd-manifest.json`, repository-relative. */
export const DEFAULT_DBD_DIRS: readonly string[] = ['.cache/experiments/maps', '.cache/experiments/terrain/refs'];

export interface GeneratedTable {
  readonly fileDataId: number;
  readonly layout: Wdc5Layout;
}

/** Reads every table's layout and FileDataID from the research copies. Throws when one is missing. */
export function readLayoutSources(repoRoot: string, dirs: readonly string[] = DEFAULT_DBD_DIRS): ReadonlyMap<LayoutTable, GeneratedTable> {
  const find = (file: string): string => {
    for (const dir of dirs) {
      const path = join(repoRoot, dir, file);
      if (existsSync(path)) return path;
    }
    throw new CascError('missing', `${file} is in none of ${dirs.join(', ')}`);
  };
  const manifest = JSON.parse(readFileSync(find('dbd-manifest.json'), 'utf8')) as readonly { readonly tableName?: string; readonly db2FileDataID?: number }[];
  const out = new Map<LayoutTable, GeneratedTable>();
  for (const table of LAYOUT_TABLES) {
    const entry = manifest.find((e) => e.tableName === table);
    if (entry?.db2FileDataID === undefined) throw new CascError('missing', `dbd-manifest.json has no db2FileDataID for ${table}`);
    const source = `WoWDBDefs ${WOWDBDEFS_COMMIT} definitions/${table}.dbd`;
    out.set(table, { fileDataId: entry.db2FileDataID, layout: layoutFromDbd(table, readFileSync(find(`${table}.dbd`), 'utf8'), LAYOUT_BUILD, source) });
  }
  return out;
}

/** True when every research copy the generator needs is present. */
export function layoutSourcesPresent(repoRoot: string, dirs: readonly string[] = DEFAULT_DBD_DIRS): boolean {
  const has = (file: string): boolean => dirs.some((dir) => existsSync(join(repoRoot, dir, file)));
  return has('dbd-manifest.json') && LAYOUT_TABLES.every((table) => has(`${table}.dbd`));
}

/** The text of `layouts.ts`: deterministic, LF, one table per entry in `LAYOUT_TABLES` order. */
export function renderLayoutsModule(tables: ReadonlyMap<LayoutTable, GeneratedTable>): string {
  const lines: string[] = [
    '/**',
    ' * GENERATED by `pnpm tsx tools/casc/make-layouts.ts` from WoWDBDefs; do not edit by hand.',
    ' *',
    ` * Source: ${WOWDBDEFS_REPOSITORY} at commit ${WOWDBDEFS_COMMIT}: the`,
    ` * \`definitions/<Table>.dbd\` block for build ${LAYOUT_BUILD} and \`manifest.json\` (FileDataIDs).`,
    ' * WoWDBDefs licenses its `definitions/` as CC BY-SA 4.0 (its LICENSE.md, same blob at that',
    ' * commit and on master, checked 2026-09-26). This file adapts those definitions (field names,',
    ' * types, sizes and order) into TypeScript data; see THIRD_PARTY_NOTICES.md "Format definitions".',
    ' */',
    "import type { Wdc5Layout } from './wdc5';",
    '',
    'export interface Db2Table {',
    '  readonly fileDataId: number;',
    '  readonly layout: Wdc5Layout;',
    '}',
    '',
    `export const LAYOUT_BUILD = '${LAYOUT_BUILD}';`,
    '',
    'export const DB2 = {',
  ];
  for (const table of LAYOUT_TABLES) {
    const entry = tables.get(table);
    if (entry === undefined) throw new CascError('missing', `no layout for ${table}`);
    const l = entry.layout;
    lines.push(`  ${table}: {`);
    lines.push(`    fileDataId: ${String(entry.fileDataId)},`);
    lines.push('    layout: {');
    lines.push(`      table: '${l.table}',`);
    lines.push(`      layoutHash: '${l.layoutHash}',`);
    lines.push(`      id: '${l.id}',`);
    lines.push(`      idInline: ${String(l.idInline)},`);
    lines.push(`      relation: ${l.relation === null ? 'null' : `'${l.relation}'`},`);
    lines.push(`      relationInline: ${String(l.relationInline)},`);
    lines.push(`      source: '${l.source}',`);
    lines.push('      fields: [');
    for (const f of l.fields) lines.push(`        { name: '${f.name}', type: '${f.type}', bits: ${String(f.bits)}, array: ${String(f.array)} },`);
    lines.push('      ],');
    lines.push('    },');
    lines.push('  },');
  }
  lines.push('} as const satisfies Record<string, Db2Table>;');
  lines.push('');
  lines.push('export type Db2TableName = keyof typeof DB2;');
  lines.push('');
  return lines.join('\n');
}
