/**
 * `public/maps/terrain/NOTICE.md` (terrain-navigation.md §13.3; D-032). Generated with the
 * manifest, from the facts it records, so a check can regenerate it offline. No timestamp, and no
 * legal conclusion.
 */

const WIDTH = 100;
const REPOSITORY_URL = 'https://github.com/laurencestokes/forever-route-lab';

function wrap(text: string, first = '', indent = ''): string {
  const lines: string[] = [];
  let line = first;
  let empty = true;
  for (const word of text.split(' ')) {
    if (!empty && line.length + 1 + word.length > WIDTH) {
      lines.push(line);
      line = indent + word;
    } else line = empty ? line + word : `${line} ${word}`;
    empty = false;
  }
  lines.push(line);
  return lines.join('\n');
}

const bullet = (text: string): string => wrap(text, '- ', '  ');

type Json = Readonly<Record<string, unknown>>;
const record = (value: unknown): Json => (typeof value === 'object' && value !== null && !Array.isArray(value) ? (value as Json) : {});
const list = (value: unknown): readonly unknown[] => (Array.isArray(value) ? value : []);

export function terrainNoticeText(manifest: Json): string {
  const client = record(manifest['client']);
  const maps = list(manifest['maps']).map(record);
  const tables = list(manifest['tables']).map(record);
  const mapList = maps.map((m) => `${String(m['name'])} (map ${String(m['mapId'])}, ${String(m['tiles'])} tiles)`).join(' and ');
  const blocks: readonly string[] = [
    '# Terrain map byproducts: notice',
    wrap(
      'Generated by `tools/terrain/byproducts.ts`. Do not edit these files by hand; regenerate them with ' +
        '`pnpm tsx tools/terrain/byproducts.ts` (it needs the pinned client at `WOW_INSTALL`); `manifest.json` records every file\'s SHA-256.',
    ),
    '## What these files are',
    wrap(
      `For ${mapList}: \`zones.json\` (zone outline arcs), \`coast.json\` (coastline arcs) and \`relief.png\` (a 4-bit shaded ` +
        'relief). They are derived by this project from the terrain data of the World of Warcraft: Forever client: the MCNK ' +
        'heightmaps, the liquid surfaces and the per-chunk `AreaTable` ids, rolled up to zones through `AreaTable.ParentAreaID`. ' +
        'They are vector outlines and a low-resolution shading computed by our own code, not copies of game files and not the ' +
        "game's painted map art (which is in `../art/` with its own notice).",
    ),
    '## Provenance',
    [
      bullet(
        `Read-only from the local client's \`Data/\` folder through this project's CASC reader (\`tools/casc\`), pinned to ` +
          `\`${String(client['product'])}\` ${String(client['version'])}, build key \`${String(client['buildKey'])}\`. Nothing is fetched from the network.`,
      ),
      bullet(`Tables: ${tables.map((t) => `\`${String(t['table'])}\` (${String(t['fileDataId'])})`).join(', ')}.`),
      bullet(
        '`manifest.json` records the tool tree hashes of `tools/terrain` and `tools/casc`, the parameters, and per map an input hash: ' +
          'SHA-256 over the sorted (FileDataID, CKey) list of the WDT, the root ADTs and those tables.',
      ),
      bullet('No ADT, WDT, DB2 or other client file is committed or deployed; only these derived files are.'),
    ].join('\n'),
    '## Owner decisions and posture',
    [
      bullet(
        'The project owner decided that these terrain-derived byproducts are committed and deployed with provenance notices ' +
          '(docs/DECISIONS.md D-032, extending D-028).',
      ),
      bullet(
        "World of Warcraft and its game data are Blizzard Entertainment's. This repository's GPL-3.0-or-later licence covers the " +
          "project's own code and grants no rights over Blizzard content or client-derived values. This is not a legal conclusion.",
      ),
    ].join('\n'),
    '## Non-affiliation',
    wrap('forever-route-lab is not affiliated with or endorsed by Blizzard Entertainment. World of Warcraft is a trademark of Blizzard Entertainment, Inc.'),
    `More: [docs/research/terrain-navigation.md](${REPOSITORY_URL}/blob/main/docs/research/terrain-navigation.md) §13 and ` +
      `[THIRD_PARTY_NOTICES.md](${REPOSITORY_URL}/blob/main/THIRD_PARTY_NOTICES.md) ("Derived terrain map data").`,
  ];
  return `${blocks.join('\n\n')}\n`;
}
