import type { LicenceCheck } from './upstream';

/**
 * NOTICE.md for public/data and the fixture slice (DATA_PROVENANCE §3.2, §7 item 2). It holds only
 * values fixed by the upstream pin (no dataRevision, tool hash or timestamp), so it is itself
 * hashed into the dataRevision. The carve-out is DATA_PROVENANCE §3.2's text, verbatim; the
 * licence finding is rendered from upstream.json `licenceCheck`.
 */

/**
 * The provenance record, as a deployed reader can follow it (the repository path is not deployed;
 * review finding data-F15).
 */
export const PROVENANCE_URL = 'https://github.com/laurencestokes/forever-route-lab/blob/main/docs/DATA_PROVENANCE.md';

/** DATA_PROVENANCE §3.2: the posture sentence (review finding data-F8). */
export const POSTURE =
  "This repository's own code is licensed GPL-3.0-or-later. Treating Questie-derived data under that licence is a posture, not a legal conclusion; it grants no rights that upstream has not granted.";

export const CARVE_OUT =
  "GPL-3.0-or-later applies to this project's contributions and, as a posture, to Questie-derived data; it grants no rights over Blizzard content (names, text, client-derived values) or other third-party material embedded in that data.";

export interface NoticeInput {
  readonly repository: string;
  readonly commit: string;
  readonly commitDate: string;
  /** The authorship line QuestieDB writes into every TOC (read from generate.lua). */
  readonly authorship: string;
  readonly dbcTarget: string;
  readonly conversionSource: string;
  /** For the fixture slice: what the slice is. Null for public/data. */
  readonly slice: string | null;
  readonly licenceCheck: LicenceCheck;
}

/**
 * Word-wraps `text` into lines of at most `width` characters (a longer word stays whole);
 * continuation lines get `indent`. The text of a Markdown link is never split.
 */
export function wrap(text: string, width: number, indent: string): readonly string[] {
  const lines: string[] = [];
  let line = '';
  // A private-use character stands in for the spaces of a link while splitting (it is not \s).
  const protectedText = text.replace(/\[[^\]]*\]\([^)]*\)/g, (link) => link.replace(/ /g, ''));
  for (const word of protectedText.split(/\s+/).filter((w) => w !== '').map((w) => w.replace(//g, ' '))) {
    const candidate = line === '' ? word : `${line} ${word}`;
    if (candidate.length > width - (lines.length === 0 ? 0 : indent.length) && line !== '') {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line !== '') lines.push(line);
  return lines.map((l, index) => (index === 0 ? l : `${indent}${l}`));
}

/** `docs/DATA_PROVENANCE.md §3.1` → a link to the deployed-readable URL, keeping the section. */
function linkEvidence(evidence: string): string {
  const match = /^docs\/DATA_PROVENANCE\.md(.*)$/.exec(evidence);
  return match === null ? evidence : `[DATA_PROVENANCE.md${match[1] ?? ''}](${PROVENANCE_URL})`;
}

const capitalise = (text: string): string => `${text.charAt(0).toUpperCase()}${text.slice(1)}`;

/** Reads the `## Author:` line QuestieDB's generate.lua writes into every TOC. */
export function readAuthorship(generateLua: string): string {
  const match = /out:write\("## Author: ([^"\\]+)\\n"\)/.exec(generateLua);
  if (match?.[1] === undefined) throw new Error('generate.lua: the "## Author:" line was not found');
  return match[1];
}

export function renderNotice(input: NoticeInput): string {
  const lines = [
    input.slice === null ? '# Notice: generated QuestieDB-derived dataset' : '# Notice: generated QuestieDB-derived test fixture',
    '',
    input.slice === null
      ? 'The files in this directory are generated by `tools/questiedb` from'
      : 'The files in this directory are a slice of the dataset `tools/questiedb` generates from',
    `[Questie/QuestieDB](${input.repository}), flavour **Forever**, at commit`,
    `\`${input.commit}\` (${input.commitDate}).`,
    '',
    'Do not edit; regenerate with `pnpm data:extract`. No file here is edited by hand.',
    '',
    ...(input.slice === null ? [] : ['## What this slice is', '', input.slice, '']),
    '## Licence finding (no legal conclusion)',
    '',
    ...wrap(`- ${capitalise(input.licenceCheck.result)} (${input.licenceCheck.method}, ${input.licenceCheck.date}; ${linkEvidence(input.licenceCheck.evidence)}).`, 96, '  '),
    ...(input.licenceCheck.note === null ? [] : wrap(`- ${capitalise(input.licenceCheck.note)}.`, 96, '  ')),
    "- Questie's unmerged `license` branch (commits `ce65498c`, 2023-02-13, to `842201bd`,",
    '  2024-05-06) drafts a notice saying that Questie historically never had a licence and that,',
    '  when in doubt, it should be considered "all rights reserved". The same draft proposes a',
    '  contributor licence agreement to license contributions as MIT, or CC0 where MIT is not',
    '  applicable.',
    '- The owner of this repository decided to build, commit and publish this derived dataset with',
    '  these notices, and accepts the risk (decision D-016).',
    '',
    '## Licence posture',
    '',
    `> ${CARVE_OUT}`,
    '',
    ...wrap(POSTURE, 96, ''),
    '',
    '## Authorship and declared origins',
    '',
    `- Upstream authorship line (QuestieDB \`generate.lua\`): "${input.authorship}".`,
    '- Questie/QuestieDB contributors: ids, relations, levels, flags and corrections.',
    '- Blizzard game content, via QuestieDB: entity names, quest text (`objectivesText`), zone and',
    '  dungeon names. Objective labels and event text are Blizzard text or text written in',
    "  QuestieDB's corrections; the two are not distinguished.",
    '- Blizzard client-derived values, via QuestieDB: AreaID to UiMapID links and the Era to',
    `  Forever coordinate projection (client DBC exports, builds ${input.conversionSource} and`,
    `  ${input.dbcTarget}).`,
    '- Item quest starts (`startsQuest`) set by QuestieDB `itemStartFixes.lua`, which declares that',
    '  it was "automatically generated from wowhead data" (owner decision OD-7 pending; shipped by',
    '  default). The items concerned are listed in `manifest.json` (`provenance.itemStartFixesOnly`).',
    '- Quest XP (`xp`, basis `era-seed`): an Era seed; upstream does not state where the values',
    '  come from.',
    '- Derived by forever-route-lab from QuestieDB data, with rules of its own: `dungeonQuest` (a',
    "  classification of QuestieDB's dungeon list), the AreaID link classes in `zones.json`, and the",
    "  entrances' `frameVerified` flags (from QuestieDB's coordinate audit).",
    "- Not included: QuestieDB's drop-percentage tables (declared Wowhead- and CMaNGOS-generated).",
    '',
    'The same origins are listed per file in `manifest.json` (`outputs[].origins`).',
    '',
    '## What this data is',
    '',
    'The Classic Era QuestieDB baseline with an Era to Forever map-coordinate projection on four',
    'zones. No Forever-specific quest, NPC, object or item content exists upstream yet: every record',
    'has `foreverStatus: "unknown"` and the manifest says `foreverContentVerified: false`.',
    '',
    '## Non-affiliation',
    '',
    'forever-route-lab is not affiliated with or endorsed by Blizzard Entertainment or the Questie',
    'project. World of Warcraft is a trademark of Blizzard Entertainment, Inc.',
    '',
    '## More',
    '',
    '- `manifest.json`: the pin, input checksums, layers, per-file hashes, origins and counts.',
    `- [docs/DATA_PROVENANCE.md](${PROVENANCE_URL}): the full provenance record.`,
    '',
  ];
  return lines.join('\n');
}
